### ISSUE TITLE
Fancy Errors!

### ISSUE THREAD

**Issue by Techcable** [jsinger67/parol#1]
Hi! This crate looks pretty incredible! 😮 

I'm working on a small DSL. I would like fancy error reporting (like the Rust compiler gives).

There are some really cool libraries that already do this:
- [miette](https://github.com/zkat/miette) - Seems general-purpose 
-  [ariadne](https://lib.rs/crates/ariadne) - seems focused specifically on compilers
- [codespan-reporting](https://github.com/brendanzab/codespan) - Also focused on compilers

All of them print pretty errors just like the Rust compiler 😄 

Have you considered adding some integration for one of those libraries (possibly behind a feature flag)?

I know this might be a lot to ask for, but at this point, it seems like it's mostly just hooking things together.

I would happy to try and work on this if you could maybe point me in the right direction. How does parol handle errors right now and how would I go about plugging in one of those "fancy error" crates?

**Comment by jsinger67** [comment]
Hi Techcable,

thank you very much for your interest in parol.
And you actual point to a current weakness in this library.

Error handling is made in the simplest way. When finding an error the parse process terminates with some rather flaky hints.
When production prediction fails due to wrong token in the input it lists the expected tokens. This is done with the help of the lookahead DFAs. They can be reinterpreted because they 'know' these expected tokens.

No attempt for recovery is made currently.

I will have a look at the libraries you named and give you my opinion about them, soon.

Anyway, if you have some concrete ideas I would like to appreciate your help.

**Comment by jsinger67** [comment]
Hi Techcable,

I'm currently incorporating miette.
Seems to be a good choice for me currently.

Thanks again for pointing me at it.

I'll let you know when this feature is ready.

**Comment by jsinger67** [comment]
**Good news 🥇** 
As of `parol v0.5.0` + `parol_runtime v0.5.2` we're using `miette` for structured error reporting.

Have fun and feel free to give any feedback 👍

**Comment by Techcable** [comment]
Thank you so much! The new errors look great :)
