### ISSUE TITLE
Generic grammar traits

### ISSUE THREAD

**Issue by nblei** [jsinger67/parol#350]
Jörg,

It would be useful to have the following:

```rust
pub trait <name>GrammarTrait {
    type RESULT=();
    type ERROR=();

    fn <non-terminal>(&mut self, _arg: &<non-terminal>) -> Result<Result<Self::RESULT, Self::ERROR>> {
        Ok((()))
    }
...
```

**Comment by jsinger67** [comment]
I see.
The problem is that the parser calls the semantic actions and needs to handle the errors right.
I'll check if there's a viable solution for it 😊

**Comment by nblei** [comment]
Thanks, Jörg.

This would be very nice because currently, to pass information through the AST requires creating some other data structure to store the information, which can be quite ackward!

**Comment by nblei** [comment]
Probably has to be `type RESULT;`, return value of `Result<Option<Self::RESULT>>` and default implementation of `Ok(None)`

**Comment by jsinger67** [comment]
Sounds like a plan 👍

**Comment by jsinger67** [comment]
Hi @nblei,
To fully grasp your intent, could you give me a small example of the type of problem you're currently struggling with?
Maybe it can be solved with the possibilities we already have. That's at least my hope 😊.

**Comment by jsinger67** [comment]
I recomment you to implement only a view sematic actions where symbol play a role and collect the information for later evaluation.
Than do the actual evaluation in the semantic action of the start symbol.
This action is called at the end of the parsing process.
Or, instead of using a semantic action for the final evaluation you also can provide an extra function that can be called after successfull parse.
This depends on the structure of your application and on your preferences.
