### ISSUE TITLE
It appears the `--only-lookahead` option (-c) doesn't work

### ISSUE THREAD

**Issue by Techcable** [jsinger67/parol#4]
I run`parol -c -f ./src/parser/parol-grammar.par -e ./src/parser/parol-grammar-exp.par -p ./src/parser/parol_parser.rs -a ./src/parser/parol_grammar_trait.rs -t ParolGrammar -m parser::parol_grammar` and there's no output (it just changes files)

Actually, I don't see anything printing unless it's in verbose mode. In that case, I see way too much :(

I've tried some other combinations of flags too, nothing seems to work. I'm pretty sure it's broken (or at least super unclear on how to use it).

Consider removing it and switching to the use of the `calculate_k` tool.

**Comment by jsinger67** [comment]
Yes, I agree.
This switch is rather unclear and it's use is dated back in the early stages of `parol`.

I plan to switch to clap 3.0 soon. In the course of this I will cleanup these quirks.

Hint: In my opinion the `decidable` subcommand is even better than `calculate_k` because you can recognize conflicts much better.

**Comment by jsinger67** [comment]
Fixed by commit [b302c92f2bcf9b64562ec219f628df5944576c8a]
