### ISSUE TITLE
User types for productions require repetition

### ISSUE THREAD

**Issue by Muon** [jsinger67/parol#490]
Currently I'm having to do
```
sliceValInner
    : integer
    | variable
    ;

sliceVal : sliceValInner : crate::ast::SliceVal;
```
When I would much rather like to do
```
sliceVal : (integer | variable) : crate::ast::SliceVal;
```
Can the user type syntax be extended to be able to apply to a whole production rule rather than just the nearest use of a nonterminal/terminal?

**Comment by jsinger67** [comment]
Hi @Muon,

first I would like to mention that you can also define aliases for the user type names by inserting
as many `%user_type` directives as you want.
In your case this could be done this way:
```parol
%user_type SliceVal = crate::ast::SliceVal
```
Then you can use them this way in your productions:
```parol
integer: /[-+]?(0|[1-9][0-9]*)/  : SliceVal;
variable: /[a-zA-Z_][a-zA-Z0-9_]*/  : SliceVal;
```

Now to your concern.

The short answer is unfortunately no -  at least currently.

The current situation is that `parol` is only able to modify types of **members** of structures
and not of whole structures whose type has to be derived from the structure of productions.
The reason here is the way it builds structures during parse time by popping items from the parse
stack and fill them in newly created structures.
During this process possible conversions are applied to these items if their types are user
defined types before they are built in the target type.

To implement a user type assignment to a complete productions the following must be changed.
When building a data structure that has a user type that differs from the originally type derived
from the structure of the associated production it must first instantiate a variable of the original
type. Then it has to retrieve the constituting members from the parse stack as described above,
apply possible necessary conversions, build the members into the struct, convert the created struct
into its user type and finally put this type on the parse stack. This would imply to change the so
called **output type** of the generated user function (i.e. the type it puts on the parse stack
after being finished). Also it creates the need to add the user type of the production to the
generated AST enum.

This is a lot to do and that's why `parol` has chosen the current way of implementation.

I don't say that from the user's perspective this wouldn't be desirable. And I also don't say that
such an improvement is impossible. All I say is that such changes can generate a lot of effort.

Now I want to elaborate a bit about your example.

As described above, the user types are made for assigning special members of a generated data type a
deviating user type.
The necessary conversion between the source type and the user type is done by a user provided
implementation of the trait `TryFrom<&ScrType> for UserType`.

The production `integer` in the upper example will then create a struct in this way:

```rust
///
/// Type derived for non-terminal integer
///
#[allow(dead_code)]
#[derive(Builder, Debug, Clone)]
#[builder(crate = "parol_runtime::derive_builder")]
pub struct Integer {
    pub integer: crate::ast::SliceVal, /* [-+]?(0|[1-9][0-9]*) */
}
```

If you wouldn't give a user type, e.g. such:
```parol
integer: /[-+]?(0|[1-9][0-9]*)/;
```

the created type would have been built up this way:
```rust
///
/// Type derived for non-terminal integer
///
#[allow(dead_code)]
#[derive(Builder, Debug, Clone)]
#[builder(crate = "parol_runtime::derive_builder")]
pub struct Integer<'t> {
    pub integer: Token<'t>, /* [-+]?(0|[1-9][0-9]*) */
}
```

Here I give you the example with which I analyzed this scenario. First the straightforward way
which needs to provide a
```rust
impl<'t> TryFrom<&'t Token<'t>> for SliceVal
```

```parol
%start Muon
%user_type SliceVal = crate::ast::SliceVal

%%

Muon: sliceValInner;

sliceValInner
    : integer
    | variable
    ;

integer: /[-+]?(0|[1-9][0-9]*)/  : SliceVal;
variable: /[a-zA-Z_][a-zA-Z0-9_]*/  : SliceVal;
```

Here is a slightly different version witch needs to provide a
```rust
impl<'t> TryFrom<&'t SliceValInner<'t>> for SliceVal
```

```parol
%start Muon
%user_type SliceVal = crate::ast::SliceVal

%%

Muon: sliceValInner: SliceVal;

sliceValInner
    : integer
    | variable
    ;

integer: /[-+]?(0|[1-9][0-9]*)/;
variable: /[a-zA-Z_][a-zA-Z0-9_]*/;
```
This variant is principally equivalent to the one above, provided that the implementations of 
`TryFrom` are equivalent.

I hope, with the help of the given explanations you find a satisfactory way for your grammar
implementation.

Feel free to give feedback or raise questions.

**Comment by jsinger67** [comment]
No further feedback.
I close the issue with "won't fix".
