### ISSUE TITLE
Does anyhow have become mandatory?

### ISSUE THREAD

**Issue by dalance** [jsinger67/parol#55]
I'm tring to migrate to v0.16.0, and got the following errors at all type convertion.

```
error[E0271]: type mismatch resolving `<VerylToken as TryFrom<&generated::veryl_grammar_trait::StartToken>>::Error == anyhow::Error`
     --> crates/parser/src/generated/veryl_grammar_trait.rs:12882:18
      |
12882 |                 .try_into()
      |                  ^^^^^^^^ expected enum `Infallible`, found struct `anyhow::Error`
```

Now should I use `TryFrom` with `anyhow::Error`?

**Comment by dalance** [comment]
I undestand. `anyhow::Error` is required because `ParolError::UserError` is `anyhow::Error`.

**Comment by jsinger67** [comment]
@dalance 
Sorry for this inconvenience.
Formerly I used `miette` as opaque error handling crate.
`miette` is great, but with this I forced all users to choose `miette` in their generated parsers, too.
That's why I dropped `miette` and used `anyhow` instead. As a PoC I used `codespan` for error reporting in the `parol` binary.
With `anyhow` as return type for user errors you get such errors when user types are converted from generated AST types.
To remedy this you have to define the `TryFrom::Error` type to be `anyhow::Error`.
You can have a look at the `basic_interpreter` example where the new error handling approach is implemented.
Here you can see the newly available better integration of user errors into the reporting process (`impl Report for BasicErrorReporter`).

OT:
How is your experience regarding performance (build and parsing) of `parol` in your `veryl` project?
As far as I know you are the first user of `parol` that launches a bigger LL(3) grammar.
I will hopefully find more time investigating in performance optimization.

**Comment by dalance** [comment]
Thank you for your explanation.
Update to v0.16.0 was finished successfully.

About performance, I found the bottoleneck.
I'll share it by another issue.
